### PR TITLE
[STORY/WS-1] Implement empty waktu solat placeholder

### PR DESCRIPTION
**Pull request by hrzyusoff**
In this PR:
* Create empty placeholder asset
* Implement data loader
* Implement time duration

### CODE REVIEW

**Review by harizyusoff — COMMENTED** [review]
Need to remove unused assets and codes. Please fix cli error messages too.

**Comment by hrzyusoff** [comment]
> Need to remove unused assets and codes. Please fix cli error messages too.

Okay got it !

**Review by hrzyusoff — COMMENTED** [review]
@harizyusoff I fixed it here, can have a look

**Review by harizyusoff — APPROVED** [review]

**Review by harizyusoff — APPROVED** [review]
Looks good, can proceed. Remember to rename commit message from "[WS-1]" to "WS-1: " on next PR

**Pull request merged**
